create schema local_test;

create table local_test."user"
(
    uid            bigint generated by default as identity
        constraint user_pk
            primary key,
    "NAME"         varchar,
    user_sex       varchar,
    balance        numeric(12, 2),
    user_state     varchar,
    configuration  varchar,
    create_ts      timestamp(3),
    last_update_ts timestamp(3)
);

create unique index user_name_uk
    on local_test."user" ("NAME");

create table local_test."house"
(
    hid            bigint not null
        constraint house_pk
            primary key,
    location       varchar,
    create_ts      timestamp(3),
    last_update_ts timestamp(3)
);

-- 手动获取序列用
create sequence local_test.house_hid_seq;
