package io.github.soupedog.jpa.config;

import hygge.commons.spring.config.configuration.definition.HyggeSpringConfigurationProperties;
import lombok.Generated;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.boot.context.properties.ConfigurationProperties;

/**
 * @author Xavier
 * @date 2023/8/15
 * @since 1.0
 */
@Getter
@Setter
@Generated
@NoArgsConstructor
@ConfigurationProperties(prefix = "example.database")
public class DatabaseConfiguration implements HyggeSpringConfigurationProperties {
    /**
     * <a href="https://dev.mysql.com/doc/connector-j/8.1/en/connector-j-time-instants.html">mysql 驱动时区问题</a>
     * <p>
     * 此处的配置是：对于驱动支持的时间对象，自动将应用生成的时间转化为数据库服务端等效的时间对象并落库
     */
    private String url = "jdbc:mysql://localhost:3306/local_test?preserveInstants=true&connectionTimeZone=SERVER";
    private String userName = "root";
    private String password = "0000";
    private Boolean autoGenerateDdl = true;
    private Boolean showSql = true;
}
